package proj.graph;

/**
 * GraphNode
 *
 * Represents a single node (vertex) in the routing graph.
 * A node is a geographic location — either a segment endpoint
 * or an intersection point where two segments pass near each other.
 *
 * Node IDs are generated by rounding lat/lng to 4 decimal places
 * (~11 metres precision), which absorbs GPS noise so two points
 * that are very close together map to the same node ID.
 */
public class GraphNode {

    public final String nodeId;
    public final double lat;
    public final double lng;

    // How this node was created — useful for debugging and dissertation analysis
    public enum NodeType {
        SEGMENT_START,       // first point of a segment
        SEGMENT_END,         // last point of a segment
        INTERSECTION         // intermediate point shared between two segments
    }

    public final NodeType type;

    public GraphNode(double lat, double lng, NodeType type) {
        this.lat    = lat;
        this.lng    = lng;
        this.type   = type;
        this.nodeId = generateId(lat, lng);
    }

    /**
     * Generates a stable string ID from coordinates.
     * Rounding to 4 decimal places gives ~11 metre precision,
     * meaning two GPS points within ~11m produce the same ID
     * and are treated as the same node in the graph.
     *
     * Source: GPS decimal precision —
     * https://blis.com/precision-matters-critical-importance-decimal-places-five-lowest-go/
     */
    public static String generateId(double lat, double lng) {
        double roundedLat = Math.round(lat * 10000.0) / 10000.0;
        double roundedLng = Math.round(lng * 10000.0) / 10000.0;
        return String.format("N_%.4f_%.4f", roundedLat, roundedLng);
    }

    @Override
    public String toString() {
        return String.format("GraphNode[id=%s, lat=%.5f, lng=%.5f, type=%s]",
            nodeId, lat, lng, type);
    }
}